# frozen_string_literal: true

source "https://rubygems.org"

gem "rake", "~> 13.0"

gem 'grape', '~> 1.5'
gem "zeitwerk", "~> 2.4"
gem "trailblazer", '~> 2.1'
gem "multi_json", "~> 1.15"
gem "representable", "~> 3.1"
gem "dry-validation"

gem "trailblazer-endpoint", path: "../../"
gem "trailblazer-activity-dsl-linear", github: "yogeshjain999/trailblazer-activity-dsl-linear", branch: "inherit-supported-wirings"

group(:test) do
  gem "rack-test"
  gem "minitest-line"
end
